# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKei-uOBX2bRCSUniDtcdFABZUrNfCwK
"""
print("Experimental Unapproved treatments for Covid-19")
import requests
from bs4 import BeautifulSoup
url="https://go.drugbank.com/covid-19#drugs"
page=requests.get(url)
Soup=BeautifulSoup(page.content,"html.parser")
Work=Soup.find_all('table')
Done=Work[2].find_all('a')
Calculation=1
for i in Done:
  Calculation=Calculation+1
  print(i.text)
  if Calculation>10:
    break
